### ISSUE TITLE
i have some things i could add, if you are still using this project i would like to make some changes

### ISSUE THREAD

**Issue by ArkAngeL43** [neelpatel05/gocrackzip#3]
i feel like this code can be definitetly remade in so many ways, and i have some general ideas. instead of making a git change or pull request i was wodering if yall would like to collaborate? maybe talk over discord or something 

that is again if this project is still being maintained

**Comment by ArkAngeL43** [comment]
alright thanks!, what would you prefer we chat on if you have any suggested platforms? i could do it hear ofc i just feel another app might be a bit more appropriate

**Comment by neelpatel05** [comment]
Let's just use Discord. I will create an account.

**Comment by ArkAngeL43** [comment]
very well then, here is my tag

```
Totally_Not_A_Hacker_ˁ˙•͡ᴥ˙•ˀ#7355
```

**Comment by neelpatel05** [comment]
Hey, I have remade the tool introducing thread via goroutines and a better usable and installable CLI tool. Please provide some feedback.
